package owlfroggy.terracottaclient.api;

public enum APIErrorCode {
    GENERIC_ERROR,
    INTERNAL_ERROR,
    MALFORMED_MESSAGE,
    NO_PERMISSION,

    TOKEN_ALREADY_PROVIDED,
    ALREADY_AUTHENTICATING,
    AUTHENTICATION_DENIED,

    INVALID_TOKEN,
    INVALID_MODE,

    NOT_IN_DEV,
    AT_SPAWN,

    SCAN_IN_PROGRESS,
    SCAN_FAILED,

    EDIT_IN_PROGRESS,
    EDIT_FAILED,

    NO_SPACE,
    INVALID_ITEM_DATA
}
